REM BACKUP ORCLVLP,JURIS2000,ORACLEWEB,FORMACION
REM  
REM ING.ESVANNY VILLARROEL
REM 
REM SEINTEX - CARACAS
REM TEAM DBA
REM
REM D:\LOGS_ORCL???_29102004	


REM BACKUP_ACONTECIMIENTOS
EXP JURIS2000/PASSWORD@ORCL??? FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ACONTECIMIENTOS.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ACONTECIMIENTOS.LOG TABLES=(ACONTECIMIENTOS) CONSISTENT=Y
PROMPT BACKUP DE ACONTECIMIENTOS COMPLETO

REM BACKUP ASUNTOS
EXP JURIS2000/PASSWORD@ORCL??? FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ASUNTOS.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ASUNTOS.LOG TABLES=(ASUNTOS) CONSISTENT=Y
PROMPT BACKUP DE ASUNTOS COMPLETO

REM BACKUP DACONOT
EXP JURIS2000/PASSWORD@ORCL??? FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\DACONOT.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\DACONOT.LOG TABLES=(DACONOT) CONSISTENT=Y
PROMPT BACKUP DE DACONOT COMPLETO

REM BACKUP DOCUMENTOS_ACTUACION
EXP JURIS2000/PASSWORD@ORCL??? FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\DOCUMENTOS_ACTUACION.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\DOCUMENTOS_ACTUACION.LOG TABLES=(DOCUMENTOS_ACTUACION) CONSISTENT=Y
PROMPT BACKUP DE DOCUMENTOS_ACTUACION COMPLETO

REM BACKUP INTERVINIENTES
EXP JURIS2000/PASSWORD@ORCL??? FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\INTERVINIENTES.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\INTERVINIENTES.LOG TABLES=(INTERVINIENTES) CONSISTENT=Y
PROMPT BACKUP DE INTERVINIENTES COMPLETO

REM BACKUP JURIS2000
EXP EXPJURIS/EXPJURIS@ORCLCVR OWNER=JURIS2000 FILE=D:\JURIS2000.DMP LOG=D:\JURIS2000.LOG  CONSISTENT=Y
PROMPT BACKUP DE JURIS2000

REM BACKUP ORACLEWEB
EXP EXPJURIS/EXPJURIS@ORCL??? OWNER=ORACLEWEB FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ORACLEWEB.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ORACLEWEB.LOG  CONSISTENT=Y
PROMPT BACKUP DE ORACLEWEB

REM BACKUP FORMACION
EXP EXPJURIS/EXPJURIS@ORCL??? OWNER=FORMACION FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\FORMACION.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\FORMACION.LOG  CONSISTENT=Y
PROMPT BACKUP DE FORMACION


REM BACKUP ORCL???
EXP EXPJURIS/EXPJURIS@ORCL??? FILE=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ORCL???.DMP LOG=C:\Instalacion_Sedes\0.Resource\RESPALDOS\LOGS\ORCL???.LOG BUFFER=3000000 FULL=Y CONSISTENT=Y
PROMPT BACKUP DE BASE DE DATOS COMPLETO

EXIT



