DROP USER ECOLOGICAL CASCADE;
 
CREATE USER ECOLOGICAL IDENTIFIED BY "ECOLOGICAL";
   
GRANT CONNECT  TO ECOLOGICAL;
GRANT RESOURCE TO ECOLOGICAL;
GRANT ROL_JR2K TO ECOLOGICAL;
GRANT UNLIMITED TABLESPACE TO ECOLOGICAL;

